apiVersion: v1
kind: Service
metadata:
  name: merch-service
spec:
  ports:
    - port: {{ .Values.merchService.ports[0].servicePort }}
      targetPort: {{ .Values.merchService.ports[0].containerPort }}
  selector:
    app: merch-service
