apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: avito-kafka
spec:
  serviceName: avito-kafka
  replicas: 1
  selector:
    matchLabels:
      app: avito-kafka
  template:
    metadata:
      labels:
        app: avito-kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.0
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: avito-zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://avito-kafka:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: avito-kafka
spec:
  ports:
    - port: 9092
  selector:
    app: avito-kafka
