apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: avito-zookeeper
spec:
  serviceName: avito-zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: avito-zookeeper
  template:
    metadata:
      labels:
        app: avito-zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.4.0
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181

---
apiVersion: v1
kind: Service
metadata:
  name: avito-zookeeper
spec:
  ports:
    - port: 2181
  selector:
    app: avito-zookeeper
