apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - port: {{ .Values.authService.ports[0].servicePort }}
      targetPort: {{ .Values.authService.ports[0].containerPort }}
  selector:
    app: auth-service
