apiVersion: v1
kind: Service
metadata:
  name: info-service
spec:
  ports:
    - port: {{ .Values.infoService.ports[0].servicePort }}
      targetPort: {{ .Values.infoService.ports[0].containerPort }}
  selector:
    app: info-service
