apiVersion: v1
kind: Service
metadata:
  name: coins-service
spec:
  ports:
    - port: {{ .Values.coinsService.ports[0].servicePort }}
      targetPort: {{ .Values.coinsService.ports[0].containerPort }}
  selector:
    app: coins-service
