apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  ports:
    - port: {{ .Values.apiGateway.ports[0].servicePort }}
      targetPort: {{ .Values.apiGateway.ports[0].containerPort }}
  selector:
    app: api-gateway
