apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: {{ .Values.userService.ports[0].servicePort }}
      targetPort: {{ .Values.userService.ports[0].containerPort }}
  selector:
    app: user-service
