"""init

Revision ID: 1cde7dfa8857
Revises: 
Create Date: 2025-02-13 19:08:56.519790

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cde7dfa8857"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token", sa.UUID(), nullable=False),
        sa.Column("user_agent", sa.VARCHAR(length=200), nullable=False),
        sa.Column("ip", sa.VARCHAR(length=39), nullable=False),
        sa.Column("expires_in", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("sessions_pkey")),
        sa.UniqueConstraint("refresh_token", name=op.f("sessions_refresh_token_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    # ### end Alembic commands ###
