name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - master
    paths:
      - "services/api-gateway/**"
      - "services/auth-service/**"
      - "services/coins-service/**"
      - "services/info-service/**"
      - "services/merch-service/**"
      - "services/user-service/**"

jobs:
    api-gateway:
        if: contains(github.event.head_commit.message, 'api-gateway') || contains(github.event.head_commit.modified, 'services/api-gateway/')
        uses: ./.github/workflows/api-gateway.yml

    auth-service:
        if: contains(github.event.head_commit.message, 'auth-service') || contains(github.event.head_commit.modified, 'services/auth-service/')
        uses: ./.github/workflows/auth-service.yml

    coins-service:
        if: contains(github.event.head_commit.message, 'coins-service') || contains(github.event.head_commit.modified, 'services/coins-service/')
        uses: ./.github/workflows/coins-service.yml

    info-service:
        if: contains(github.event.head_commit.message, 'info-service') || contains(github.event.head_commit.modified, 'services/info-service/')
        uses: ./.github/workflows/info-service.yml

    merch-service:
        if: contains(github.event.head_commit.message, 'merch-service') || contains(github.event.head_commit.modified, 'services/merch-service/')
        uses: ./.github/workflows/merch-service.yml

    user-service:
        if: contains(github.event.head_commit.message, 'user-service') || contains(github.event.head_commit.modified, 'services/user-service/')
        uses: ./.github/workflows/user-service.yml
