name: User Service Tests

on:
  workflow_call:

env:
  VERSION: 1.0.${{ github.run_number }}

jobs:
  lint:
    name: Lint User Service Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run --timeout 5m

  test:
    name: Run User Service Tests
    runs-on: ubuntu-latest
    needs: lint

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          until docker info; do sleep 1; done

      - name: Build and run tests
        run: |
          docker compose -f docker-compose-test.yml up --build user-service-test
          docker_exec_exit_code=$(docker inspect -f '{{.State.ExitCode}}' avito-user-service-test)
          exit $docker_exec_exit_code
